project_id = "iadhangnqjkyyxuerkyc"
[functions.create-cart-checkout]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-recurring-checkout]
verify_jwt = false

[functions.connect-onboard]
verify_jwt = false

[functions.connect-status]
verify_jwt = false
